[GD-48] feat : 사용자가 받은 링크로 이벤트를 조회하는 기능 구현
prgrms-web-devcourse/Team_DOKEV_GOLDDDUCK_BE pull request #7
Opened 2021-12-02 04:50 UTC by GetMapping

## 📌 이슈 설명 
[GD-48](https://maenguin.atlassian.net/browse/GD-48)
## ✅ PR 포인트 & 궁금한 점 
- [x] EventResponse : 이벤트 조회시 데이터를 담는 응답 객체를 만들었습니다.
- [x] EventConverter : event객체를 응답객체로 변환시킨 뒤 ApiResponse 객체로 반환해주는 converter를 구현했습니다.
- [x] EventService : findDetailEvent가 단일 이벤트를 조회하는 메소드입니다.

2021-12-02 05:21 UTC, choiyoungkwon12 requested changes
서비스에 대한 테스트가 없습니다 작성 부탁드립니다.

2021-12-02 05:21 UTC, choiyoungkwon12 commented on src/main/java/com/dokev/gold_dduck/event/service/EventService.java
> +        }
연관관계 편의 메서드는 조회할 때 없어도 될 것 같습니다.

2021-12-02 05:21 UTC, choiyoungkwon12 commented on src/main/java/com/dokev/gold_dduck/event/dto/EventConverter.java
> +        return ApiResponse.success(eventResponse);
여기서 ApiResponse로 감싸준 이유가 있을까요?? ApiResponse로 만드는 작업은 컨트롤러에서 하는게 좋을까요? 아니면 컨버터 할 때 하는게 좋은지 비교해보면 좋을 것 같습니다.

2021-12-02 05:21 UTC, maenguin reviewed
언주님 감동적인 첫 기능에 대한 코드네요
일단 테스트 코드도 추가해주세요 ㅎㅎ

2021-12-02 05:21 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/event/dto/EventResponse.java
> +    private List<Gift> gifts = new ArrayList<>();
응답에 엔티티를 그대로 반환하지 말고 dto로 변환해서 보내면 좋을것 같아요!

2021-12-02 05:21 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/event/service/EventService.java
> +        List<Gift> gifts = eventRepository.findGiftsByEventId(event.getId());
조인으로 쿼리를  하나로 묶어볼 수 있을것 같습니다

2021-12-02 05:21 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/event/repository/EventRepository.java
> +    Event findEventByCode(@Param("code") UUID code);
메소드명으로  쿼리를 생성하면 @Param를 안붙여도 인식이 됩니다!

2021-12-02 05:21 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/event/repository/EventRepository.java
> +    List<Gift> findGiftsByEventId(Long eventId);
반대로 여기서는 @param붙여야 파라미터를 인식합니다!

2021-12-02 05:21 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/event/dto/EventConverter.java
> +        return ApiResponse.success(eventResponse);
컨버터는 엔티티 <-> dto 변환만 수행하고
ApiResponse는 컨트롤러에서 담도록 하는게 좋을 것 같습니다!

2021-12-02 05:42 UTC, choiyoungkwon12 commented on src/main/java/com/dokev/gold_dduck/event/repository/EventRepository.java
> +    @Query(value = "SELECT a FROM Gift AS a WHERE a.event = :eventId")
```suggestion
    @Query(value = "SELECT g FROM Gift AS g WHERE g.event = :eventId")
```
a보단 Gift니까 g가 더 좋을 것 같습니다.

2021-12-02 05:42 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/event/repository/EventRepository.java
> +    Event findEventByCode(@Param("code") UUID code);
리턴타입을 Optional 감싸면 좋을 것 같습니다!

2021-12-05 08:09 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/member/dto/MemberResponseDto.java
> +
기본 생성자 넣어주세요 NoArgusConstructor(access = PROTECTED)

2021-12-05 08:11 UTC, maenguin commented on src/main/java/com/dokev/gold_dduck/member/repository/MemberRepository.java
> +    @Query(value = "SELECT distinct e From Event e JOIN FETCH e.member")
프로젝션에 e가 아니라 m이 오도록 해주세요!
value 안써도 괜찮습니다!

2021-12-06 09:42 UTC, closed without merging